apiVersion: v1
kind: Service
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  selector:
    app: strapi
  ports:
    - name: http
      protocol: TCP
      port: 1337
      targetPort: 1337
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  selector:
    matchLabels:
      app: strapi
  replicas: 1
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: ghcr.io/pavluninvladimir/telegrambot:0.0.2
          ports:
            - name: http
              containerPort: 1337
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "strapi"
            - name: DATABASE_USERNAME
              value: "strapi_user"
            - name: DATABASE_PASSWORD
              value: "strapi_password"
      imagePullSecrets:
        - name: ghcr-secret