name: Сборка, тегирование и создание Docker контейнера

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v2

    # - name: Установка Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    # - name: Установка зависимостей
    #   run: npm install

    # - name: Сборка Strapi проекта
    #   run: npm run build

    - name: Получение имени ветки
      id: get_branch_name
      run: echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"

    - name: Получение текущей версии
      id: get_version
      run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

    - name: Инкрементирование версии
      id: increment_version
      run: |
        echo "::set-output name=version::$(node -p " \
          const semver = require('semver'); \
          const version = require('./package.json').version; \
          const newVersion = version.split('.').map((v, i) => (i === 2 ? parseInt(v) + 1 : v)).join('.'); \
          newVersion \
        ")"

    - name: Обновление package.json
      run: |
        echo "::set-output name=version::${{ steps.increment_version.outputs.version }}"
        sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.increment_version.outputs.version }}\"/" package.json
    
    - name: Гит статус
      run: git status

    - name: Тегирование коммита
      run: git tag ${{ steps.increment_version.outputs.version }}
      
    - name: Добавление изменений в коммит
      run: git add .

    - name: Создание коммита
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Обновление версии в package.json"

    - name: Пуш изменений в текущую ветку
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git push origin ${{ steps.get_branch_name.outputs.branch }}

    - name: Создание Docker контейнера
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-docker-username/your-docker-repo:${{ steps.increment_version.outputs.version }}